name: Pack when tagged

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Archive files
        run: git archive --format tar.gz --output "./devenv.tar.gz" main

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref }}
          artifact: devenv.tar.gz
          draft: true
          token: ${{ secrets.GH_TOKEN }}
